import type { MapSpawn } from "./types";

const spawns: MapSpawn[] = [
  // --- map-groudon ---
  {
    mapId: "map-groudon",
    neutralId: "groudon",
    left: "50.29%",
    top: "38.11%",
    spawnTime: "02:00",
    respawnTime: 0,
    permanentDelete: false,
    infoKey: "groudon.boss",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "16.36%",
    top: "47.47%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "16.36%",
    top: "34.6%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "22.21%",
    top: "58%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "23.38%",
    top: "25.24%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "32.74%",
    top: "65.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "33.91%",
    top: "19.39%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "84.22%",
    top: "47.47%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "83.05%",
    top: "34.6%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "78.37%",
    top: "58%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "76.03%",
    top: "25.24%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "67.84%",
    top: "65.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "66.67%",
    top: "19.39%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "50.06%",
    top: "13.54%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_940",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "56.84%",
    top: "12.37%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "42.8%",
    top: "12.37%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "48.89%",
    top: "75.55%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_940",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "51.7%",
    top: "75.55%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_940",
  },
  {
    mapId: "map-groudon",
    neutralId: "bunnelby",
    left: "50.06%",
    top: "59.76%",
    spawnTime: "09:15",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_915",
  },
  {
    mapId: "map-groudon",
    neutralId: "accelgor",
    left: "33.8%",
    top: "49.23%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-groudon",
    neutralId: "accelgor",
    left: "65.85%",
    top: "49.23%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-groudon",
    neutralId: "escavalier",
    left: "33.8%",
    top: "31.68%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "escavalier",
  },
  {
    mapId: "map-groudon",
    neutralId: "escavalier",
    left: "66.79%",
    top: "31.68%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "escavalier",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "26.07%",
    top: "35.77%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.generic",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "25.61%",
    top: "46.89%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.generic",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "73.46%",
    top: "35.77%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.generic",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "74.04%",
    top: "46.89%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.generic",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "56.84%",
    top: "21.73%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "42.8%",
    top: "21.73%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "50.06%",
    top: "10.03%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "33.33%",
    top: "12.37%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_only",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "67.26%",
    top: "12.37%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_only",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "30.99%",
    top: "73.21%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "69.13%",
    top: "73.21%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_only",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "42.34%",
    top: "40.45%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "57.55%",
    top: "40.45%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "28.06%",
    top: "29.34%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "72.05%",
    top: "29.34%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "25.61%",
    top: "52.15%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "baltoy",
    left: "74.51%",
    top: "51.57%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "regidrago",
    left: "50.29%",
    top: "38.11%",
    spawnTime: "00:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regidrago",
  },
  {
    mapId: "map-groudon",
    neutralId: "regieleki",
    left: "50.06%",
    top: "7.69%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regieleki",
  },
  {
    mapId: "map-groudon",
    neutralId: "regieleki",
    left: "50.06%",
    top: "84.91%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regieleki",
  },
  {
    mapId: "map-groudon",
    neutralId: "regice",
    left: "50.06%",
    top: "0.67%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "regice",
    left: "50.06%",
    top: "91.93%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "registeel",
    left: "45.38%",
    top: "0.67%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "registeel",
    left: "45.38%",
    top: "91.93%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "regirock",
    left: "54.74%",
    top: "0.67%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "regirock",
    left: "54.74%",
    top: "91.93%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-groudon",
    neutralId: "xatu",
    left: "23.62%",
    top: "41.62%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu",
  },
  {
    mapId: "map-groudon",
    neutralId: "xatu",
    left: "76.97%",
    top: "41.62%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu",
  },
  {
    mapId: "map-groudon",
    neutralId: "natu",
    left: "50.18%",
    top: "41.04%",
    spawnTime: "09:00",
    respawnTime: 0,
    permanentDelete: true,
    despawnTime: "02:00",
    infoKey: "natu.900",
  },
  {
    mapId: "map-groudon",
    neutralId: "natu",
    left: "50.18%",
    top: "23.49%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    despawnTime: "02:00",
    infoKey: "natu.920",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "40.93%",
    top: "74.38%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "41.87%",
    top: "61.51%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "58.72%",
    top: "74.38%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "57.78%",
    top: "61.51%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "25.61%",
    top: "15.88%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "18.7%",
    top: "20.56%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "13.55%",
    top: "27.58%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "74.04%",
    top: "15.88%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "80.95%",
    top: "20.56%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "84.92%",
    top: "26.41%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "11.21%",
    top: "56.6%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "15.66%",
    top: "62.1%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "84.46%",
    top: "62.1%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "indeedee",
    left: "88.9%",
    top: "56.83%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower",
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "36.72%",
    top: "64.44%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "34.73%",
    top: "68.53%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "64.33%",
    top: "64.44%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "66.32%",
    top: "68.53%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "37.66%",
    top: "19.98%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "36.72%",
    top: "15.88%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "62.93%",
    top: "19.39%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "sitrus",
    left: "63.86%",
    top: "15.88%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-groudon",
    neutralId: "salac",
    left: "45.14%",
    top: "50.4%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac",
  },
  {
    mapId: "map-groudon",
    neutralId: "salac",
    left: "54.5%",
    top: "50.4%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac",
  },
  {
    mapId: "map-groudon",
    neutralId: "salac",
    left: "45.14%",
    top: "32.26%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac",
  },
  {
    mapId: "map-groudon",
    neutralId: "salac",
    left: "54.5%",
    top: "32.26%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac",
  },
  {
    mapId: "map-groudon",
    neutralId: "altaria",
    left: "0%",
    top: "0%",
    spawnTime: "NaN:NaN",
    respawnTime: 0,
    permanentDelete: false,
    despawnTime: "02:00",
    infoKey: "altaria.after_regidrago",
  },
  // --- map-kyogre ---
  {
    mapId: "map-kyogre",
    neutralId: "kyogre",
    left: "50.29%",
    top: "38.53%",
    spawnTime: "02:00",
    respawnTime: 0,
    permanentDelete: false,
    infoKey: "kyogre.boss",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "15.66%",
    top: "47.89%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "15.66%",
    top: "35.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "22.68%",
    top: "58.42%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "22.68%",
    top: "25.66%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "32.39%",
    top: "65.44%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "32.39%",
    top: "19.81%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "84.92%",
    top: "47.89%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "84.92%",
    top: "35.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "76.97%",
    top: "58.42%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "76.97%",
    top: "25.66%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "68.19%",
    top: "65.44%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "68.19%",
    top: "19.81%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.initial",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "50.06%",
    top: "13.96%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "56.84%",
    top: "12.79%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "42.8%",
    top: "12.79%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "48.89%",
    top: "75.97%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "51.7%",
    top: "75.97%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-kyogre",
    neutralId: "bunnelby",
    left: "50.06%",
    top: "60.17%",
    spawnTime: "09:15",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_915_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "accelgor",
    left: "25.61%",
    top: "47.3%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-kyogre",
    neutralId: "accelgor",
    left: "74.04%",
    top: "47.3%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-kyogre",
    neutralId: "escavalier",
    left: "33.8%",
    top: "32.09%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "escavalier",
  },
  {
    mapId: "map-kyogre",
    neutralId: "escavalier",
    left: "66.79%",
    top: "32.09%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "escavalier",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "26.07%",
    top: "36.19%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "33.8%",
    top: "49.06%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "73.46%",
    top: "36.19%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "65.85%",
    top: "49.06%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "56.84%",
    top: "22.15%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "42.8%",
    top: "22.15%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "50.06%",
    top: "10.45%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "33.33%",
    top: "12.79%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "67.26%",
    top: "12.79%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "30.99%",
    top: "73.63%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "69.13%",
    top: "73.63%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "42.34%",
    top: "40.87%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "57.55%",
    top: "40.87%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "28.06%",
    top: "29.75%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_kyogre",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "72.05%",
    top: "29.75%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_kyogre",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "25.61%",
    top: "52.57%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_kyogre",
  },
  {
    mapId: "map-kyogre",
    neutralId: "baltoy",
    left: "74.51%",
    top: "51.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_kyogre",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regidrago",
    left: "50.29%",
    top: "38.53%",
    spawnTime: "00:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regidrago.kyogre",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regieleki",
    left: "50.06%",
    top: "8.11%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regieleki",
    left: "50.06%",
    top: "85.33%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regice",
    left: "50.06%",
    top: "1.09%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regice",
    left: "50.06%",
    top: "92.35%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "registeel",
    left: "45.38%",
    top: "1.09%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "registeel",
    left: "45.38%",
    top: "92.35%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regirock",
    left: "54.74%",
    top: "1.09%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "regirock",
    left: "54.74%",
    top: "92.35%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-kyogre",
    neutralId: "xatu",
    left: "23.62%",
    top: "42.04%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu.short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "xatu",
    left: "76.97%",
    top: "42.04%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu.short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "natu",
    left: "50.18%",
    top: "41.45%",
    spawnTime: "09:00",
    respawnTime: 0,
    permanentDelete: true,
    despawnTime: "02:00",
    infoKey: "natu.900",
  },
  {
    mapId: "map-kyogre",
    neutralId: "natu",
    left: "50.18%",
    top: "23.9%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    despawnTime: "02:00",
    infoKey: "natu.920",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "40.93%",
    top: "74.8%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "41.87%",
    top: "61.93%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "58.72%",
    top: "74.8%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "57.78%",
    top: "61.93%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "25.61%",
    top: "16.3%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "18.7%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "13.55%",
    top: "28%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "74.04%",
    top: "16.3%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "80.95%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "84.92%",
    top: "26.83%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "11.21%",
    top: "57.01%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "15.66%",
    top: "62.51%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "84.46%",
    top: "62.51%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "indeedee",
    left: "88.9%",
    top: "57.25%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.tower_short",
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "36.72%",
    top: "64.85%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "34.73%",
    top: "68.95%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "64.33%",
    top: "64.85%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "66.32%",
    top: "68.95%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "37.66%",
    top: "20.39%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "36.72%",
    top: "16.3%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "62.93%",
    top: "19.81%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "63.86%",
    top: "16.3%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "45.14%",
    top: "50.81%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "54.5%",
    top: "50.81%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "45.14%",
    top: "32.68%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "54.5%",
    top: "32.68%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "36.72%",
    top: "42.04%",
    spawnTime: "05:00",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "sitrus",
    left: "63.4%",
    top: "42.04%",
    spawnTime: "05:00",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-kyogre",
    neutralId: "altaria",
    left: "0%",
    top: "0%",
    spawnTime: "NaN:NaN",
    respawnTime: 0,
    permanentDelete: false,
    despawnTime: "02:00",
    infoKey: "altaria.after_regidrago",
  },
  // --- map-rayquaza ---
  {
    mapId: "map-rayquaza",
    neutralId: "rayquaza",
    left: "50.1%",
    top: "39.7%",
    spawnTime: "02:00",
    respawnTime: 0,
    permanentDelete: false,
    infoKey: "rayquaza.boss",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "15.47%",
    top: "47.89%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "15.47%",
    top: "35.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "22.49%",
    top: "58.42%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "22.49%",
    top: "25.66%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "32.66%",
    top: "62.51%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "31.73%",
    top: "67.78%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "34.07%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "33.13%",
    top: "18.05%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "84.73%",
    top: "47.89%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "84.73%",
    top: "35.02%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "76.77%",
    top: "58.42%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "76.77%",
    top: "25.66%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "67.06%",
    top: "63.1%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "68%",
    top: "67.78%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "66.13%",
    top: "17.47%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "65.07%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "bunnelby.points",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "49.86%",
    top: "13.96%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "56.65%",
    top: "12.79%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "42.61%",
    top: "12.79%",
    spawnTime: "09:20",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_920_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "48.69%",
    top: "75.97%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "51.5%",
    top: "75.97%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "bunnelby",
    left: "49.86%",
    top: "60.17%",
    spawnTime: "09:15",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "bunnelby.lane_915_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "accelgor",
    left: "33.6%",
    top: "49.64%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "accelgor",
    left: "65.66%",
    top: "49.64%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "accelgor",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "escavalier",
    left: "33.6%",
    top: "32.09%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "escavalier",
    left: "66.59%",
    top: "32.09%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "25.88%",
    top: "36.19%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "25.41%",
    top: "47.3%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "73.26%",
    top: "36.19%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "73.85%",
    top: "47.3%",
    spawnTime: "09:45",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.945_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "49.98%",
    top: "23.9%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "56.65%",
    top: "22.15%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "42.61%",
    top: "22.15%",
    spawnTime: "09:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_940_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "49.86%",
    top: "10.45%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "33.13%",
    top: "12.79%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "67.06%",
    top: "12.79%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "30.79%",
    top: "73.63%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "68.93%",
    top: "73.63%",
    spawnTime: "09:10",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_910_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "42.14%",
    top: "40.87%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "57.35%",
    top: "40.87%",
    spawnTime: "08:40",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.lane_840_short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "27.87%",
    top: "29.75%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "71.86%",
    top: "29.75%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "25.41%",
    top: "52.57%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "baltoy",
    left: "74.32%",
    top: "51.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "regieleki",
    left: "49.86%",
    top: "8.11%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "regice",
    left: "49.86%",
    top: "85.33%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "registeel",
    left: "45.18%",
    top: "85.33%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "regirock",
    left: "54.54%",
    top: "85.33%",
    spawnTime: "07:00",
    respawnTime: 120,
    permanentDelete: false,
    infoKey: "regi.700",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "xatu",
    left: "23.42%",
    top: "42.04%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "xatu",
    left: "76.77%",
    top: "42.04%",
    spawnTime: "09:59",
    respawnTime: 0,
    permanentDelete: true,
    infoKey: "xatu.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "40.74%",
    top: "74.8%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "41.67%",
    top: "61.93%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "58.52%",
    top: "74.8%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_930",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "57.59%",
    top: "61.93%",
    spawnTime: "09:35",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "indeedee.lane_935",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "25.41%",
    top: "16.3%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "18.51%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "13.36%",
    top: "28%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "73.85%",
    top: "16.3%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "80.75%",
    top: "20.98%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "84.73%",
    top: "26.83%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "11.02%",
    top: "57.01%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "15.47%",
    top: "62.51%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "84.26%",
    top: "62.51%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "indeedee",
    left: "88.71%",
    top: "57.25%",
    spawnTime: "10:00",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "baltoy.tower_break",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "36.53%",
    top: "64.85%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "34.54%",
    top: "68.95%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "64.14%",
    top: "64.85%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "66.13%",
    top: "68.95%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "37.46%",
    top: "20.39%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "36.53%",
    top: "16.3%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "62.73%",
    top: "19.81%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "sitrus",
    left: "63.67%",
    top: "16.3%",
    spawnTime: "09:30",
    respawnTime: 60,
    permanentDelete: false,
  },
  {
    mapId: "map-rayquaza",
    neutralId: "salac",
    left: "44.95%",
    top: "50.81%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "salac",
    left: "54.31%",
    top: "50.81%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "salac",
    left: "44.95%",
    top: "32.68%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "salac",
    left: "54.31%",
    top: "32.68%",
    spawnTime: "08:30",
    respawnTime: 60,
    permanentDelete: false,
    infoKey: "salac.short",
  },
  {
    mapId: "map-rayquaza",
    neutralId: "altaria",
    left: "49.86%",
    top: "40.87%",
    spawnTime: "08:00",
    respawnTime: 90,
    permanentDelete: false,
    despawnTime: "02:00",
    infoKey: "altaria.rayquaza",
  }
];

export default spawns;
